#!/bin/sh

set -e

export DG_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"

echo "==> Cleaning DG applications from $DG_ROOT/applications"
"$DG_ROOT/applications/Allclean"

echo "==> Cleaning DG libraries from $DG_ROOT/src"
"$DG_ROOT/src/Allclean"

#------------------------------------------------------------------------------
