/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | www.openfoam.com
     \\/     M anipulation  |
-------------------------------------------------------------------------------
    Copyright (C) 2011-2016 OpenFOAM Foundation
    Copyright (C) 2021-2025 OpenCFD Ltd.
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Description
    Mathematical utilities for DG Gauss fields.

SourceFiles

\*---------------------------------------------------------------------------*/

#ifndef Foam_dgGaussFieldMath_H
#define Foam_dgGaussFieldMath_H

#include "dgFaceGaussFieldLiteralScalarMath.H"
#include "dgFaceGaussFieldScalarMath.H"
#include "dgFaceGaussFieldVectorMath.H"
#include "dgFaceGaussFieldTensorMath.H"

#include "dgCellGaussFieldLiteralScalarMath.H"
#include "dgCellGaussFieldScalarMath.H"
#include "dgCellGaussFieldVectorMath.H"
#include "dgCellGaussFieldTensorMath.H"

#include "dgGaussFieldLiteralScalarMath.H"
#include "dgGaussFieldScalarMath.H"
#include "dgGaussFieldVectorMath.H"
#include "dgGaussFieldTensorMath.H"

#endif

// ************************************************************************* //
