#!/bin/sh

set -e

SRC_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"

echo "==> Cleaning libDGCoreFields from $SRC_ROOT/DGCoreFields"
cd "$SRC_ROOT/DGCoreFields"
wclean libso

echo "==> Cleaning libDGMesh from $SRC_ROOT/mesh"
cd "$SRC_ROOT/mesh"
wclean libso

echo "==> Cleaning libDGFluidThermophysicalModels from $SRC_ROOT/thermophysicalModels"
cd "$SRC_ROOT/thermophysicalModels"
wclean libso

echo "==> Cleaning libDGMethod from $SRC_ROOT/DGMethod"
cd "$SRC_ROOT/DGMethod"
wclean libso

#------------------------------------------------------------------------------
