#!/bin/sh
echo "==> Cleaning mesh/"
cd mesh
wclean

echo "==> Cleaning DGFoam/"
cd ../DGFoam
wclean

echo "==> Cleaning DGMethod/"
cd ../DGMethod
wclean

echo "==> Cleaning thermophysicalModels/"
cd ../thermophysicalModels
wclean
#------------------------------------------------------------------------------
