#!/bin/sh
echo "==> Cleaning mesh/"
cd mesh
wclean

echo "==> Cleaning DGFoam/"
cd ../DGFoam
wclean

echo "==> Cleaning math/"
cd ../math
wclean

echo "==> Cleaning math/"
cd ../math
wclean
echo "==> Cleaning thermophysicalModels/"
cd ../thermophysicalModels
wclean
#------------------------------------------------------------------------------
